### DISCUSSION TITLE
Trying to run through docker

### DISCUSSION THREAD

**Discussion by rymiller11** [ep1cman/unifi-protect-backup#121] [Q&A]
I'm trying to run UPB through docker with rclone.  I have the rclone.conf file created in my home directory but it isn't recognized.  I resorted to some of the debug section to test out the consumption of rclone.conf.  Here's the command and the output:

Command:    docker run \
    --rm \
    -v /path/to/rclone.conf:/home/rymiller/rclone.conf \
    -e RCLONE_CONFIG='/home/rymiller/rclone.conf' \
    --entrypoint rclone \
    ghcr.io/ep1cman/unifi-protect-backup \
    listremotes

Here's the output:
2024/01/09 22:40:18 Failed to load config file "/home/rymiller/rclone.conf": read /home/rymiller/rclone.conf: is a directory

This doesn't make sense because it is not a directory.  I changed permissions to be wide open.

Any ideas?  Thanks!

**Comment by rymiller11** [comment]
I have lots of questions on the parameters being used to run the docker with an rclone destination.  From the instructions, here is the docker command:
docker run \
  -e UFP_USERNAME='USERNAME' \
  -e UFP_PASSWORD='PASSWORD' \
  -e UFP_ADDRESS='UNIFI_PROTECT_IP' \
  -e UFP_SSL_VERIFY='false' \
  -e RCLONE_DESTINATION='my_remote:/unifi_protect_backup' \
  -v '/path/to/save/clips':'/data' \
  -v '/path/to/rclone.conf':'/config/rclone/rclone.conf' \
  -v '/path/to/save/database':/config/database/ \
  ghcr.io/ep1cman/unifi-protect-backup

I understand the UFP_ values - no issue there.

1.  for RCLONE_DESTINATION: is my_remote the name of the remote I provided in the rclone config command?  If it is, there is an error when I run it using the rclone remote's name.
2.  for /path/to/rclone.conf : is this an [OPTION]?  Should it stay static or should I replace this with the path to my rclone.conf file?  If it stays static, then I should replace the '/config/rclone/rclone.conf' with the path to my rclone.conf file?  I have tried both but the conf file is not found.
3. same as question 2 for the database:  Is the first part an [OPTION] or should be replaced with a value?

Need some help :-).  Thanks!

**Reply by ep1cman** [reply]
1. `RCLONE_DESTINATION` is indeed the name of the rclone remote configured within the rclone conf file
2. `/path/to/rclone.conf ` should be replaced with the path to the `rclone.conf` file on your host machine, the latter part `/config/rclone/rclone.conf` should not be edited. The error message you provided clearly states that `/home/rymiller/rclone.conf: is a directory` so please check this path and make sure it is to the `.conf` file and not a directory.
3. Same as above, the left hand side should be the directory where you want the database to be stored on your host machine for persistence, the right hand side should not be edited

Also ` -e RCLONE_CONFIG='/home/rymiller/rclone.conf' ` does not make sense, you are telling rclone _inside_ the container to use the path on your host machine rather than the path inside the container.

**Reply by rymiller11** [reply]
Thanks @ep1cman .  I mistakenly thought that the left side was showing what value to put on the right side of the colon. 
i.e. '/path/to/save/database':/input/your/value/here

I'll try it now.... I'm sure it will work now.

Thanks

**Comment by rymiller11** [comment]
Bumping.... beginning to wonder if this project is active.  Anyone else using UPB successfully?

**Comment by brephil** [comment]
I'm using an lxc as a host and was confused on the rclone test in the readme.  

As mentioned above, you should only replace the _/path/to/rclone.conf_ with your actually location on the host.  

In general not familiar with running docker so maybe obvious for most but not for me.  Maybe this will help someone struggling to understand exactly what to change in the example given.  

```
docker run \
    --rm \
    -v '/root/.config/rclone/rclone.conf':'/config/rclone/rclone.conf' \
    -e RCLONE_CONFIG='/config/rclone/rclone.conf' \
    --entrypoint rclone \
    ghcr.io/ep1cman/unifi-protect-backup \
    listremotes
```

**Reply by rymiller11** [reply]
I am very frustrated that I cannot get this docker implementation to run.  Does anyone have any hints?  This is what I run from the command line and the immediate error message:

```
rymiller@upbackup:/ $ sudo docker run \
  -e UFP_USERNAME='redacted' \
  -e UFP_PASSWORD='redacted' \
  -e UFP_ADDRESS='IPRedacted' \
  -e UFP_SSL_VERIFY='false' \
  -e RCLONE_DESTINATION='cali_nas:/nvr' \
  -v '/path/to/save/clips':'/data' \
  -v '/root/.config/rclone/rclone.conf':'/config/rclone/rclone.conf' \
  -v '/home/rymiller':/config/database/ \
  ghcr.io/ep1cman/unifi-protect-backup
[migrations] started
[migrations] no migrations found
cp: cannot stat '/root/.config/rclone/rclone.conf': No such file or directory
```

I checked the /root/.config/rclone/ directory and the rclone.conf file is right there but it's not getting picked up.

I did notice that when I created the rclone.conf from the docker command that it DID NOT put the conf file into this directory so I had to copy it and I have CHMODed to make sure permissions was not a problem.  

Any ideas what my problem could be??????

**Reply by Swallowtail23** [reply]
I have no issues with this running for me, my config for files is:
```
  -v '/opt/upb-docker/data/':'/data' \
  -v '/opt/upb-docker/database/':'/config/database' \
  -v '/opt/upb-docker/conf/':'/config/rclone' \
```
Question though - is there a specific reason you are running it as root (sudo)? 
On Red Hat I run as an unprivileged user (using podman) and it works fine (there is a section in the discussions section here on my rootless setup).

**Reply by rymiller11** [reply]
i figured sudo was messing everything up.  plus running in the home directory is not cool either.... lost permissions to my home directory so now i'm staying out of that and it seems to be working now

**Reply by biofects** [reply]
I created a docker compose to help keep track of changes in my gitlab this works well for me
I have dedicated storage device for cameras and have it mounted on the machine running docker containers
```
services:
    ep1cman:
        environment:
          - UFP_USERNAME=*************  # User that was created on UDM
          - UFP_PASSWORD=************   # Password created for UDM user
          - UFP_ADDRESS=************    # Address I have a domain that I use with SSL if not use local ip of UDM
          - UFP_SSL_VERIFY=TRUE         # only if you have a valid SSL cert
          - RCLONE_RETENTION=120d       # how long yhou want to store captures on Storage
          - RCLONE_ARGS="--local-no-set-modtime"  # I have to use this argument as I use CIFS and chtime was not working 
        volumes:
          - '/Protect/cameras:/data'    # local mount:docker mount
          - '/home/user/unifi-protect/database:/config/database'  # local config/database:docker config/database 
        image: ghcr.io/ep1cman/unifi-protect-backup:latest  
        restart: unless-stopped
        pull_policy: always
        ```
        Remember to update the information above with your information.
