### ISSUE TITLE
Intermittent errors appearing for events dating a few weeks back, current events do not upload

### ISSUE THREAD

**Issue by smshapiro85** [ep1cman/unifi-protect-backup#142]
* Unifi Protect Backup version: latest
* Unifi Protect version: 3.0.26
* Python version: 3.11.8
* Operating System: linux
* Are you using a docker container or native?: Docker
* Rclone backup location: Dropbox

### Description

Scratching my head a bit on this- I am getting intermittent errors with events from 16-17 days ago (retention is set to 21d).

Here is a screenshot of a few examples of the errors. They appear to come in waves at various times throughout the day, and are errors for events that happened a while back.

Today's events do not appear to be successfully uploading either, so I am not sure if there is a backlog and I am getting rate limited with dropbox, or something else.

The only clue I have is that I was previously limiting detection types to "person, vehicle, ring" and did not appear to have any issues like this. Once I removed that restriction to allow backup of my G3 Instant cameras that do not have smart detections, I started getting these errors.

![image](https://github.com/ep1cman/unifi-protect-backup/assets/41717535/11df2816-8ba2-4ff5-876c-4c143eadb019)

![image](https://github.com/ep1cman/unifi-protect-backup/assets/41717535/c8d9c900-0831-473f-8c50-1033a5d83428)

Here is my Docker compose:
```
version: "3.7"
services:
  unifi-protect-backup:
    image: ghcr.io/ep1cman/unifi-protect-backup
    container_name: unifi-protect-backup
    environment:
      UFP_USERNAME: unifi-protect-backup
      UFP_PASSWORD: XXXXXXXXX
      UFP_ADDRESS: 192.168.1.1
      UFP_SSL_VERIFY: false
      RCLONE_DESTINATION: XXXXXXX:unifi-protect-backup-2
      RCLONE_RETENTION: 21d
      APPRISE_NOTIFIERS: ERROR=pover://XXXXXXX@XXXXXX
    volumes:
      - /volume2/dockerssd/unifi-protect-backup:/data
      - /volume2/dockerssd/unifi-protect-backup:/config/database/
      - type: bind
        source: /volume2/dockerssd/unifi-protect-backup/config/rclone/rclone.conf
        target: /config/rclone/rclone.conf
    restart: always
```
