### ISSUE TITLE
File overwrite every backup run

### ISSUE THREAD

**Issue by e36Alex** [ep1cman/unifi-protect-backup#145]
* Unifi Protect Backup version: latest
* Unifi Protect version: 3.0.26 (latest)
* Python version:
* Operating System: Linux
* Are you using a docker container or native?: Docker

### Description

I backup my protect files from docker container to a SMB share on my NAS.
Every 5 minutes all files (even existing) get a new Timestamp.
This causes, that the sync job from my NAS to OneDrive uploads all files again because it thinks there is an update.

It would be great, if just new or changed files could be updated.

### What I Did

docker-compose.yml
```
services:
  protect-backup:
    container_name: protect-backup
    image: ghcr.io/ep1cman/unifi-protect-backup:latest
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - /srv/docker-volumes/unifi-protect-backup/database:/config/database/
      - cam-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
          

volumes:
  cam-data:
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.10.72/cam-data"
      o: "username=${SMB_USER},password=${SMB_PASS},vers=3.0,file_mode=0777,dir_mode=0777"
```

.env:
```
UFP_USERNAME=xxx
UFP_PASSWORD=xxx
UFP_ADDRESS=192.168.1.1
UFP_SSL_VERIFY=false
SMB_USER=xxx
SMB_PASS=xxx
```
