### ISSUE TITLE
Error on Dev version and Latest version

### ISSUE THREAD

**Issue by biofects** [ep1cman/unifi-protect-backup#151]
* Unifi Protect Backup version: Dev
* Unifi Protect version: Protect 4.0.21
* Python version: Python 3.12.3
* Operating System: Ubuntu 24.04 LTS
* Are you using a docker container or native?: Docker

### Description

On my OS I have a mount from a storage device to store my events.  /Protect This is world readable and writable
I have tested the latest and the dev version you have released bot throw different errors

### What I Did
Dev version
Docker Compose file
```
services:
    ep1cman:
        environment:
          - UFP_USERNAME=**************
          - UFP_PASSWORD=**************
          - UFP_ADDRESS=**************
          - UFP_SSL_VERIFY=true
          - RCLONE_RETENTION=60d
        volumes:
          - '/Protect/cameras:/data'
          - '/home/user/user-scripts/unifi-protect/database:/config/database'
          - './resolv.conf:/etc/resolv.conf'
        image: ghcr.io/ep1cman/unifi-protect-backup:dev
        restart: unless-stopped
        pull_policy: always
  ````
Error
```
p1cman-1  | 2024-05-30 21:21:40 [   INFO    ] unifi_protect_backup.downloader            : [663350a701d3fe03e4012950]  Downloading event: 663350a701d3fe03e4012950
ep1cman-1  | 2024-05-30 21:21:40 [   DEBUG   ] unifi_protect_backup.downloader            : [663350a701d3fe03e4012950]  Remaining Download Queue: 0
ep1cman-1  | 2024-05-30 21:21:40 [   DEBUG   ] unifi_protect_backup.downloader            : [663350a701d3fe03e4012950]  Video Download Buffer: 0.0B/512.0MiB
ep1cman-1  | 2024-05-30 21:21:40 [   DEBUG   ] unifi_protect_backup.downloader            : [663350a701d3fe03e4012950]    Camera: Front Yard Left
ep1cman-1  | 2024-05-30 21:21:40 [   DEBUG   ] unifi_protect_backup.downloader            : [663350a701d3fe03e4012950]    Type: motion
ep1cman-1  | 2024-05-30 21:21:40 [   DEBUG   ] unifi_protect_backup.downloader            : [663350a701d3fe03e4012950]    Start: 2024-05-02T03-36-52 (1714639012.408)
ep1cman-1  | 2024-05-30 21:21:40 [   DEBUG   ] unifi_protect_backup.downloader            : [663350a701d3fe03e4012950]    End: 2024-05-02T03-37-05 (1714639025.908)
ep1cman-1  | 2024-05-30 21:21:40 [   DEBUG   ] unifi_protect_backup.downloader            : [663350a701d3fe03e4012950]    Duration: 13.5s
ep1cman-1  | 2024-05-30 21:21:40 [   DEBUG   ] unifi_protect_backup.downloader            : [663350a701d3fe03e4012950]    Downloading video...
ep1cman-1  | 2024-05-30 21:21:41 [  WARNING  ] unifi_protect_backup.downloader            : [663350a701d3fe03e4012950]  Event failed download attempt 1
ep1cman-1  | Traceback (most recent call last):
ep1cman-1  |   File "/usr/lib/python3.12/site-packages/unifi_protect_backup/downloader.py", line 144, in start
ep1cman-1  |     video = await self._download(event)
ep1cman-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ep1cman-1  |   File "/usr/lib/python3.12/site-packages/unifi_protect_backup/downloader.py", line 184, in _download
ep1cman-1  |     video = await self._protect.get_camera_video(event.camera_id, event.start, event.end)
ep1cman-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ep1cman-1  |   File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 1206, in get_camera_video
ep1cman-1  |     return await self.api_request_raw(
ep1cman-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ep1cman-1  |   File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 249, in api_request_raw
ep1cman-1  |     await self._os.verify_response(url, response)
ep1cman-1  |   File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 331, in verify_response
ep1cman-1  |     await self.clear_auth()
ep1cman-1  |   File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 424, in clear_auth
ep1cman-1  |     await self.session_cache.delete_session(session_hash)
ep1cman-1  |   File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 143, in delete_session
ep1cman-1  |     cache = await self.read_session_cache()
ep1cman-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ep1cman-1  |   File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 77, in read_session_cache
ep1cman-1  |     async with aiofiles.open(self.session_cache, "rb") as f:
ep1cman-1  |   File "/usr/lib/python3.12/site-packages/aiofiles/base.py", line 98, in __aenter__
ep1cman-1  |     self._obj = await self._coro
ep1cman-1  |                 ^^^^^^^^^^^^^^^^
ep1cman-1  |   File "/usr/lib/python3.12/site-packages/aiofiles/threadpool/__init__.py", line 94, in _open
ep1cman-1  |     f = yield from loop.run_in_executor(executor, cb)
ep1cman-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ep1cman-1  |   File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
ep1cman-1  |     result = self.fn(*self.args, **self.kwargs)
ep1cman-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ep1cman-1  | PermissionError: [Errno 13] Permission denied: '/root/.cache/ufp/sessions.json'
```
