### ISSUE TITLE
rclone does not have a remote called `Blah`

### ISSUE THREAD

**Issue by JonLaliberte** [ep1cman/unifi-protect-backup#170]
* Unifi Protect Backup version: 0.11.0
* Unifi Protect version: NA
* Are you using a docker container or native?: Docker

### Description
When I start the container, I get an error: "rclone does not have a remote called `Blah`"

### What I Did
I figured this was a permissions issue, so I entered the container: 
`docker exec -it opt_unifi-protect-backup_1 /bin/bash`

And I checked that the config file was readable and it was:
```
# cat rclone.conf
[Blah]
type = Z
account = X
key = Y
hard_delete = true
```

Docker config:
```
  unifi-protect-backup:
    image: ghcr.io/ep1cman/unifi-protect-backup
    environment:
      - UFP_USERNAME=XXX
      - UFP_PASSWORD=XXX
      - UFP_ADDRESS=XXX
      - UFP_SSL_VERIFY=false
      - RCLONE_DESTINATION=Blah
      - RCLONE_RETENTION=100y
      - PURGE_INTERVAL=1w
    volumes:
      - /unifi-protect-backup/clips:/data
      - /unifi-protect-backup/database:/config/database
      - /unifi-protect-backup/rclone.conf:/config/rclone/rclone.conf
    restart: unless-stopped
```

I ran:
```
docker run \
    --rm \
    -v /unifi-protect-backup/rclone.conf:/config/rclone/rclone.conf \
    -e RCLONE_CONFIG='/config/rclone/rclone.conf' \
    --entrypoint rclone \
    ghcr.io/ep1cman/unifi-protect-backup \
    listremotes
```

And it printed:
```
Blah:
```
