### ISSUE TITLE
Connecting to a remote Unifi Protect

### ISSUE THREAD

**Issue by stantyan** [ep1cman/unifi-protect-backup#206]
Hi, does anyone know if it is possible to host [unifi-protect-backup](https://github.com/ep1cman/unifi-protect-backup) on a cloud machine in docker and pull files from a remote Unifi Protect located in office?

Office Unifi Protect on UDM <-> unifi-protect-backup on VPS <-> send videos via rclone to cloud storage

Locally deployed unifi-protect-backup just needs to know local IP of the Unifi Protect. Maybe it is possible to use Tailsclale to setup a link between remote Unifi Protect and cloud VPS?

**Comment by ep1cman** [comment]
It should be totally doable so long as there is network access between the two machines. A VPN tunnel of some kind should do the job (please don't put your UDM on the public internet 😝)

**Comment by stantyan** [comment]
@ep1cman I am a bit lost with paths if using rclone remote as a destination. Here is my compose:
```
services:
    unifi-protect-backup:
        image: ghcr.io/ep1cman/unifi-protect-backup:latest
        environment:
            - UFP_USERNAME=${UFP_USERNAME}
            - UFP_PASSWORD=${UFP_PASSWORD}
            - UFP_ADDRESS=${UFP_ADDRESS}
            - UFP_SSL_VERIFY=${UFP_SSL_VERIFY}
            - RCLONE_DESTINATION=${RCLONE_DESTINATION}
            - EXPERIMENTAL_DOWNLOADER=${EXPERIMENTAL_DOWNLOADER}
            - FILE_STRUCTURE_FORMAT=${FILE_STRUCTURE_FORMAT}
            - RCLONE_RETENTION=${RCLONE_RETENTION}
            - DETECTION_TYPES=${DETECTION_TYPES}
            - DOWNLOAD_BUFFER_SIZE=${DOWNLOAD_BUFFER_SIZE}
            - CAMERAS=${CAMERAS}
            - SKIP_MISSING=${SKIP_MISSING}
        volumes:
            - /mnt/nas_share_drive/streams/security-cameras/unifi:/data
            - /root/.config/rclone/rclone.conf:/config/rclone/rclone.conf
            - unifi-protect-backup-database:/config/database/
        restart: unless-stopped

volumes:
    unifi-protect-backup-database:
```

Assume my` RCLONE_DESTINATION = my-google-drive:/surveillance`

How should I update  my previous path where I saved videos to a local NAS shared drive `/mnt/nas_share_drive/streams/surveillance/unifi:/data`, should it be like this?
```
volumes:
            - /unifi:/data
```

or like this
```
volumes:
            - my-google-drive:/surveillance/unifi:/data
```
